# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.

services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      # Generates a base64-encoded key for
      # encrypting credentials in n8n
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Host & protocol for your custom domain
      - key: N8N_HOST
        value: n8n.umbrellafreedom.com
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n.umbrellafreedom.com/

      # Database connection settings
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user

databases:
  - name: n8n-db
    plan: free
    # Optional: set disk size if upgrading
    # diskSizeGB: 5
